include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_returning_null_for_future: true
    always_put_control_body_on_new_line: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    cascade_invocations: true
    combinators_ordering: true
    eol_at_end_of_file: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
