name: addonsly
description: Helpful Flutter addons like widgets, constants, extensions, etc.
version: 0.0.5

homepage: https://github.com/ephmoc/addonsly
repository: https://github.com/ephmoc/addonsly
issue_tracker: https://github.com/ephmoc/addonsly/issues

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
